# Generated by Django 3.1.4 on 2020-12-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('to', models.CharField(max_length=30, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('stop1', models.CharField(max_length=30, null=True)),
                ('stop2', models.CharField(max_length=30, null=True)),
                ('stop3', models.CharField(max_length=30, null=True)),
                ('stop4', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='createpass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('Busno', models.CharField(max_length=30, null=True)),
                ('From', models.CharField(max_length=30, null=True)),
                ('To', models.CharField(max_length=30, null=True)),
                ('Date1', models.DateField(max_length=100)),
                ('Date2', models.DateField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('profile_pic', models.ImageField(default='', upload_to='profiles')),
                ('cc_number', models.IntegerField(null=True)),
                ('cvv', models.IntegerField(default=123)),
                ('expiry', models.CharField(max_length=100, null=True)),
                ('month', models.IntegerField(default=2020)),
            ],
        ),
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('uemail', models.CharField(max_length=100)),
            ],
        ),
    ]
