# Generated by Django 3.1.4 on 2020-12-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpass',
            old_name='pass_id',
            new_name='id',
        ),
    ]
