# Generated by Django 3.1.4 on 2020-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0002_auto_20201209_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpass',
            name='qr_codes',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
