# Generated by Django 3.1.4 on 2020-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0003_createpass_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpass',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
