# Generated by Django 3.1.4 on 2020-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0005_remove_createpass_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpass',
            name='qr_codes',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
