# Generated by Django 3.1.4 on 2020-12-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0006_createpass_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpass',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
