# Generated by Django 3.1.4 on 2020-12-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0007_createpass_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpass',
            name='otp',
        ),
    ]
