# Generated by Django 3.1.4 on 2020-12-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0008_remove_createpass_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateTimeField(max_length=100),
        ),
    ]
