# Generated by Django 3.1.4 on 2020-12-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0009_auto_20201215_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateField(max_length=100),
        ),
    ]
