# Generated by Django 3.1.4 on 2020-12-15 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0011_auto_20201215_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='renewpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('Busno', models.CharField(max_length=30, null=True)),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('From', models.CharField(max_length=30, null=True)),
                ('To', models.CharField(max_length=30, null=True)),
                ('Date1', models.DateField(max_length=100)),
                ('Date2', models.DateField(default=datetime.datetime(2021, 1, 14, 10, 50, 55, 298876))),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 10, 50, 55, 296847)),
        ),
    ]
