# Generated by Django 3.1.4 on 2020-12-15 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0013_auto_20201215_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='renewpass',
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 12, 36, 57, 134040)),
        ),
    ]
