# Generated by Django 3.1.4 on 2020-12-15 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0014_auto_20201215_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 14, 2, 29, 772171)),
        ),
    ]
