# Generated by Django 3.1.4 on 2020-12-15 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0016_auto_20201215_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 14, 10, 45, 668368)),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 14, 10, 45, 668368)),
        ),
    ]
