# Generated by Django 3.1.4 on 2020-12-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0020_auto_20201215_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateTimeField(),
        ),
    ]
