# Generated by Django 3.1.4 on 2020-12-15 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0021_auto_20201215_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 9, 6, 9, 44065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 9, 6, 9, 44065, tzinfo=utc)),
        ),
    ]
