# Generated by Django 3.1.4 on 2020-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0023_auto_20201215_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='Date2',
            field=models.CharField(max_length=50),
        ),
    ]
