# Generated by Django 3.1.4 on 2020-12-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0025_auto_20201219_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='cc_number',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
