# Generated by Django 3.1.4 on 2020-12-19 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0026_auto_20201219_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.CharField(default=datetime.datetime(2020, 12, 20, 0, 0, 44, 205330), max_length=50, null=True),
        ),
    ]
