# Generated by Django 3.1.4 on 2020-12-19 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0027_auto_20201220_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.CharField(default=datetime.datetime(2020, 12, 20, 0, 1, 52, 595810), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createpass',
            name='cc_number',
            field=models.IntegerField(null=True),
        ),
    ]
