# Generated by Django 3.1.4 on 2020-12-21 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0028_auto_20201220_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.CharField(default=datetime.datetime(2020, 12, 21, 16, 27, 31, 455503), max_length=50, null=True),
        ),
    ]
