# Generated by Django 3.1.4 on 2020-12-21 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0030_auto_20201221_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.CharField(default=datetime.datetime(2020, 12, 21, 17, 4, 17, 968861), max_length=50, null=True),
        ),
    ]
