# Generated by Django 3.1.4 on 2021-01-14 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vedant_Bus_app', '0031_auto_20201221_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpass',
            name='Date1',
            field=models.CharField(default=datetime.datetime(2021, 1, 14, 21, 11, 59, 263938), max_length=50, null=True),
        ),
    ]
